# Generated by Django 5.1.7 on 2025-03-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_password',
        ),
    ]
