# Generated by Django 5.1.6 on 2025-02-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trials.trial'),
        ),
    ]
